disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - line_length
 - force_cast
 - xctfail_message
 - nesting
 - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods